# Part of LibXtract
#
# SPDX-FileCopyrightText: 2014 Jamie Bullock
# SPDX-License-Identifier: Zlib

NAME = simpletest

.PHONY: $(NAME) clean

$(NAME):
	@$(MAKE) -C $@

install:
	@$(MAKE) -C $(NAME) install


clean:
	@$(MAKE) -C $(NAME) clean
